# Generated by Django 6.1.1 on 2026-09-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, upload_to='resumes/'),
        ),
    ]
