# Generated by Django 6.1.1 on 2026-09-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
